using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace CustomSearchesEFLibrary.CustomSearches.Model
{
    public partial class CustomSearchExpression
    {
        public int CustomSearchExpressionId { get; set; }
        public Guid? DatasetId { get; set; }
        public int? CustomSearchColumnDefinitionId { get; set; }
        public int? CustomSearchParameterId { get; set; }
        public int? DatasetPostProcessId { get; set; }
        public int? DatasetChartId { get; set; }
        public int? ProjectTypeId { get; set; }
        public string OwnerType { get; set; }
        public string ExpressionType { get; set; }
        public string ExpressionRole { get; set; }
        public string Script { get; set; }
        public string ColumnName { get; set; }
        public int? ExceptionPostProcessRuleId { get; set; }
        public string Note { get; set; }
        public string Category { get; set; }
        public int? RscriptModelId { get; set; }
        public string ExpressionGroup { get; set; }
        public int ExecutionOrder { get; set; }
        public int? CustomSearchValidationRuleId { get; set; }
        public int? ChartTemplateId { get; set; }
        public string ExpressionExtensions { get; set; }
        public bool IsAutoGenerated { get; set; }

        public virtual ChartTemplate ChartTemplate { get; set; }
        public virtual CustomSearchColumnDefinition CustomSearchColumnDefinition { get; set; }
        public virtual CustomSearchParameter CustomSearchParameter { get; set; }
        public virtual CustomSearchValidationRule CustomSearchValidationRule { get; set; }
        public virtual Dataset Dataset { get; set; }
        public virtual InteractiveChart DatasetChart { get; set; }
        public virtual DatasetPostProcess DatasetPostProcess { get; set; }
        public virtual ExceptionPostProcessRule ExceptionPostProcessRule { get; set; }
        public virtual ExpressionRole ExpressionRoleNavigation { get; set; }
        public virtual ExpressionType ExpressionTypeNavigation { get; set; }
        public virtual OwnerType OwnerTypeNavigation { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual RscriptModel RscriptModel { get; set; }
    }
}
