// <copyright file="DynamicsHttpRequestException.cs" company="King County">
//  Copyright (c) King County. All rights reserved.
// </copyright>

namespace DynamicsToSQLBlazor.Data
{
    using System;

    /// <summary>
    /// Model for error generated by Http request.
    /// </summary>
    public class DynamicsHttpRequestException : Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DynamicsHttpRequestException"/> class.
        /// Model for throwing error from CrmODatahelper class.
        /// </summary>
        /// <param name="message"> the error message generated for odata request to dynamics environment.</param>
        /// <param name="innerException"> The exception that comes from inner code.</param>
        public DynamicsHttpRequestException(string message, Exception innerException)
            : base(message, innerException)
        {
        }
    }
}