// <auto-generated />
namespace PTASDynamicsWebhook
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Azure.WebJobs;
    using Microsoft.Azure.WebJobs.Extensions.Http;
    using Microsoft.Extensions.Logging;

    public static class TestDelta
    {
        [FunctionName("TestDelta")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            string name = req.Query["name"];
            try
            {
                await DeltaQueueChecker.Run(name, log);
                return new OkObjectResult("Finished executing delta on entity " + name);
            }
            catch (Exception ex)
            {
                return new OkObjectResult(ex.Message);
            }

        }
    }
}