// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "SA1200:Using directive should appear within a namespace declaration", Justification = "AutoGenerated Files", Scope = "module")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasCamaModel")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasCamaModel")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasCamaModel")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1028:Code should not contain trailing whitespace", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasCamaModel")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1507:Code should not contain multiple blank lines in a row", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasCamaModel")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Code should not contain multiple blank lines in a row", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasCamaModel")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1404:Code analysis suppression should have justification", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasCamaModel")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasCamaModel")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasCamaModel")]

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasTreasuryModel")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasTreasuryModel")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasTreasuryModel")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1028:Code should not contain trailing whitespace", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasTreasuryModel")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1507:Code should not contain multiple blank lines in a row", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasTreasuryModel")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Code should not contain multiple blank lines in a row", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasTreasuryModel")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1404:Code analysis suppression should have justification", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasTreasuryModel")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasTreasuryModel")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasTreasuryModel")]

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasHistoricalModel")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasHistoricalModel")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasHistoricalModel")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1028:Code should not contain trailing whitespace", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasHistoricalModel")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1507:Code should not contain multiple blank lines in a row", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasHistoricalModel")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Code should not contain multiple blank lines in a row", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasHistoricalModel")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1404:Code analysis suppression should have justification", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasHistoricalModel")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasHistoricalModel")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "PTASODataLibrary.PtasDbDataProvider.PtasHistoricalModel")]