namespace PTASMapTileServicesLibrary.TileProvider.Exception
{
    using System;

    /// <summary>
    /// Exception generated by the tile feature data provider.
    /// </summary>
    /// <seealso cref="System.Exception" />
    public class TileFeatureDataProviderException : System.Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TileFeatureDataProviderException" /> class.
        /// </summary>
        /// <param name="exceptionCategory">Category of the exception.</param>
        /// <param name="tileFeatureDataProviderType">Type of the tile feature data provider that generated the exception.</param>
        /// <param name="message">The exception message.</param>
        /// <param name="innerException">The inner exception.</param>
        /// <exception cref="System.ArgumentNullException">When tileProviderType is null.</exception>
        public TileFeatureDataProviderException(TileFeatureDataProviderExceptionCategory exceptionCategory, Type tileFeatureDataProviderType, string message, System.Exception innerException)
            : base(message, innerException)
        {
            if (tileFeatureDataProviderType == null)
            {
                throw new ArgumentNullException(nameof(tileFeatureDataProviderType));
            }

            this.TileFeatureDataProviderExceptionCategory = exceptionCategory;
            this.TileFeatureDataProviderType = tileFeatureDataProviderType;
        }

        /// <summary>
        /// Gets the category of the tile exception.
        /// </summary>
        public TileFeatureDataProviderExceptionCategory TileFeatureDataProviderExceptionCategory { get; }

        /// <summary>
        /// Gets the type of the tile feature data provider that generated the exception.
        /// </summary>
        public Type TileFeatureDataProviderType { get; }
    }
}