namespace PTASMapTileServicesLibrary.TileProvider.Exception
{
    using System;

    /// <summary>
    /// Exception generated by the GeoLocation provider.
    /// </summary>
    /// <seealso cref="System.Exception" />
    public class GeoLocationProviderException : System.Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoLocationProviderException" /> class.
        /// </summary>
        /// <param name="exceptionCategory">Category of the exception.</param>
        /// <param name="message">The exception message.</param>
        /// <param name="innerException">The inner exception.</param>
        public GeoLocationProviderException(GeoLocationProviderExceptionCategory exceptionCategory, string message, System.Exception innerException)
            : base(message, innerException)
        {
            this.GeoLocationProviderExceptionCategory = exceptionCategory;
        }

        /// <summary>
        /// Gets the category of the exception.
        /// </summary>
        public GeoLocationProviderExceptionCategory GeoLocationProviderExceptionCategory { get; }
    }
}