
IF NOT EXISTS (SELECT [FolderType] FROM [gis].[FolderType] WHERE [FolderType] = 'SystemRenderer')
	INSERT [gis].[FolderType] ([FolderType]) VALUES (N'SystemRenderer')

GO --1. Re-Add new SystemRenderer Folder Type

EXEC SP_DropColumn_With_Constraints '[cus].[CustomSearchParameter]', 'AllowMultipleSelection'
ALTER TABLE [cus].[CustomSearchParameter] ADD [AllowMultipleSelection] [bit] NOT NULL DEFAULT 0

GO -- #2. Add [AllowMultipleSelection] field to [CustomSearchParameter] table


IF NOT EXISTS (SELECT [ExpressionRole] FROM [cus].[ExpressionRole] WHERE [ExpressionRole] = 'UpdateStoredProcedure')
	INSERT [cus].[ExpressionRole] ([ExpressionRole]) VALUES (N'UpdateStoredProcedure')

GO --3. Add UpdateStoredProcedure expression role

EXEC SP_DropColumn_With_Constraints  '[cus].[CustomSearchExpression]', 'IsAutoGenerated'
ALTER TABLE [cus].[CustomSearchExpression] ADD [IsAutoGenerated] [bit] NOT NULL DEFAULT 0

GO -- #4. Add [IsAutoGenerated] field to [CustomSearchExpression] table

DROP procedure IF EXISTS dbo.[SP_DropColumnConstraint];
GO -- #5. Drop[SP_DropColumnConstraint] stored procedure

CREATE procedure [dbo].[SP_DropColumnConstraint] @schema_name nvarchar(256), @table_name nvarchar(256), @col_name nvarchar(256)
AS

DECLARE @command  nvarchar(1000)

select @Command = 'ALTER TABLE ' + @schema_name + '.[' + @table_name + '] DROP CONSTRAINT ' + d.name
 from sys.tables t
  join sys.default_constraints d on d.parent_object_id = t.object_id
  join sys.columns c on c.object_id = t.object_id and c.column_id = d.parent_column_id
 where t.name = @table_name
  and t.schema_id = schema_id(@schema_name)
  and c.name = @col_name

--print @Command

execute (@Command)


GO -- #6. Create [SP_DropColumnConstraint] stored procedure

EXEC SP_DropColumnConstraint 'cus', 'CustomSearchParameter', 'ParameterDefaultValue'
GO -- #7. Remove default value constraint for ParameterDefaultValue from CustomSearchParameter

