
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SRCH_GetAreaData')
	DROP PROCEDURE [cus].[SRCH_GetAreaData]  
GO

CREATE PROCEDURE [cus].[SRCH_GetAreaData]
  @Area		   smallint	= NULL
 ,@SubArea	   smallint	= NULL
 ,@AssmtYr	   smallint	= NULL
 ,@SalesFrom   smalldatetime	= NULL
 ,@SalesTo	   smalldatetime	= NULL
 ,@SalePrice   int		= NULL
 ,@Population  char(3)         = 'N'
 ,@Notes       char(3)         = 'N'
 ,@Filtered	   Char(3) 		   = 'N' -- "N" : runs the search as the regular GetAreaData Search / "Y": Runs the search inclusding the results like the ones generated by the old Macro
		
AS 
BEGIN
/*
Author: Jairo Barquero
Date Created: 12/04/2020
Description:    SP that Inserts data into #SalesPop, #RealProp, #Sales, #Land, #XLand, #TaxAcctReceivable

Modifications:
mm/dd/yyy - [CREATED BY] : [DETAILED DESCRIPTION OF THE CHANGE]
*/
SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED



CREATE TABLE #SalesPopFinal(
	[ID] [bigint] NOT NULL,
	[ParcelId] [uniqueidentifier] NULL,
	[LandGuid] [uniqueidentifier] NULL,	
	[SaleGuid] [uniqueidentifier] NULL,
	[BldgGuid] [uniqueidentifier] NULL,	
	[SaleId] [nvarchar](50) NULL,
	[ResArea] [char](3) NULL,
	[ResSubarea] [char](3) NULL,
	[PropType] [varchar](1) NOT NULL,
	[QSec] [char](2) NULL,
	[Sec] [tinyint] NULL,
	[Twn] [tinyint] NULL,
	[Rng] [tinyint] NULL,
	[Neighborhood] [smallint] NULL,
	[GisSurfaceValue] [varchar](14) NULL,
	[Folio] [char](7) NULL,
	[PlatLot] [char](14) NULL,
	[PlatBlock] [char](7) NULL,
	[Major] [char](6) NULL,
	[Minor] [char](4) NULL,
	[LocationAddr] [varchar](46) NOT NULL,
	[StreetNbr] [varchar](5) NULL,
	[NbrFraction] [varchar](3) NULL,
	[DirPrefix] [char](2) NULL,
	[StreetName] [varchar](25) NULL,
	[StreetType] [char](4) NULL,
	[DirSuffix] [char](2) NULL,
	[DistrictName] [varchar](80) NULL,
	[TaxpayerName] [varchar](80) NULL,
	[SellerName] [varchar](300) NULL,
	[BuyerName] [varchar](300) NULL,
	[ExciseTaxNbr] [int] NULL,
	[SaleYear] [int] NULL,
	[SaleMonth] [int] NULL,
	[SaleDate] [smalldatetime] NULL,
	[SalePrice] [int] NULL,
	[VerifiedAtMkt] [char](1) NULL,
	[VerifiedBy] [char](4) NULL,
	[Reason] [tinyint] NULL,
	[Instr] [tinyint] NULL,
	[PrinUse] [tinyint] NULL,
	[PropClass] [tinyint] NULL,
	[Warnings] [nvarchar](max) NULL,
	[PossibleLenderSale] [char](1) NULL,
	[HoldoutReason] [varchar](50) NOT NULL,
	[SelectDate] [smalldatetime] NULL,
	[SelectAppr] [char](4) NULL,
	[SelectMethod] [varchar](50) NULL,
	[SelectReason] [varchar](50) NULL,
	[SelectLandVal] [int] NULL,
	[SelectImpsVal] [int] NULL,
	[SelectValTotal] [int] NULL,
	[RollLandVal] [int] NULL,
	[RollImpsVal] [int] NULL,
	[RollValTotal] [int] NULL,
	[BaseLandVal] [int] NULL,
	[BaseLandValTaxYr] [smallint] NULL,
	[BaseLandValDate] [smalldatetime] NULL,
	[BldgRCN] [int] NULL,
	[BldgRCNLD] [int] NULL,
	[AccyRCN] [int] NULL,
	[AccyRCNLD] [int] NULL,
	[MHRCN] [int] NULL,
	[MHRCNLD] [int] NULL,
	[TotalRCN] [int] NULL,
	[TotalRCNLD] [int] NULL,
	[ImpCnt] [int] NULL,
	[BldgNbr] [tinyint] NULL,
	[NbrLivingUnits] [tinyint] NULL,
	[SqFtLot] [int] NULL,
	[SqFtLotDry] [int] NULL,
	[SqFtLotSubmerged] [int] NULL,
	[Age] [int] NULL,
	[YrBuilt] [smallint] NULL,
	[YrRenovated] [smallint] NULL,
	[BldgGrade] [tinyint] NULL,
	[BldgGradeVar] [tinyint] NULL,
	[Condition] [tinyint] NULL,
	[SqFtTotLiving] [int] NULL,
	[SqFtAboveGrLiving] [int] NULL,
	[BathTotal] [numeric](8, 2) NULL,
	[FpTotal] [tinyint] NULL,
	[SqFtCoveredParking] [int] NULL,
	[Stories] [real] NULL,
	[SqFt1stFloor] [int] NULL,
	[SqFtHalfFloor] [int] NULL,
	[SqFt2ndFloor] [int] NULL,
	[SqFtUpperFloor] [int] NULL,
	[SqFtUnfinFull] [int] NULL,
	[SqFtUnfinHalf] [int] NULL,
	[SqFtTotBasement] [int] NULL,
	[SqFtFinBasement] [int] NULL,
	[FinBasementGrade] [tinyint] NULL,
	[SqFtGarageBasement] [int] NULL,
	[SqFtGarageAttached] [int] NULL,
	[DaylightBasement] [char](1) NULL,
	[Bedrooms] [tinyint] NULL,
	[BathHalfCount] [tinyint] NULL,
	[Bath3qtrCount] [tinyint] NULL,
	[BathFullCount] [tinyint] NULL,
	[FpSingleStory] [tinyint] NULL,
	[FpMultiStory] [tinyint] NULL,
	[FpFreestanding] [tinyint] NULL,
	[FpAdditional] [tinyint] NULL,
	[PcntComplete] [tinyint] NULL,
	[PcntNetCondition] [tinyint] NULL,
	[Obsolescence] [tinyint] NULL,
	[SqFtOpenPorch] [int] NULL,
	[SqFtEnclosedPorch] [int] NULL,
	[SqFtDeck] [int] NULL,
	[HeatSystem] [tinyint] NULL,
	[HeatSource] [tinyint] NULL,
	[BrickStone] [tinyint] NULL,
	[AddnlCost] [int] NULL,
	[DetGarArea] [int] NULL,
	[DetGarGrade] [tinyint] NULL,
	[DetGarEffYr] [smallint] NULL,
	[DetGarNetCond] [tinyint] NULL,
	[CarportArea] [int] NULL,
	[CarportEffYr] [smallint] NULL,
	[CarportNetCond] [tinyint] NULL,
	[PoolArea] [int] NULL,
	[PoolEffYr] [smallint] NULL,
	[PoolNetCond] [tinyint] NULL,
	[paving] [int] NULL,
	[MiscAccyCost] [int] NULL,
	[DevCost] [int] NULL,
	[Flatvalue] [int] NULL,
	[MHCount] [int] NULL,
	[MHBldgNbr] [tinyint] NULL,
	[MHType] [varchar](9) NOT NULL,
	[MHClass] [tinyint] NULL,
	[MHLength] [int] NULL,
	[MHWidth] [int] NULL,
	[MHLivingArea] [int] NULL,
	[MHTipOutArea] [int] NULL,
	[MHRoomAddSqft] [int] NULL,
	[MHSize] [int] NULL,
	[MHYrBuilt] [int] NULL,
	[MHCondition] [tinyint] NULL,
	[MHPcntNetCondition] [int] NULL,
	[ZoneClass] [varchar](50) NULL,
	[CurrentZoning] [varchar](50) NULL,
	[ZoneDesignation] [varchar](50) NULL,
	[ZoningChgDate] [smalldatetime] NULL,
	[HBUAsIfVacant] [tinyint] NULL,
	[HBUasImproved] [tinyint] NULL,
	[PresentUse] [smallint] NULL,
	[WaterSystem] [tinyint] NULL,
	[SewerSystem] [tinyint] NULL,
	[Access] [tinyint] NULL,
	[Topography] [tinyint] NULL,
	[StreetSurface] [tinyint] NULL,
	[PcntBaseLandValImpacted] [int] NULL,
	[Unbuildable] [smallint] NULL,
	[RestrictiveSzShape] [tinyint] NULL,
	[MtRainier] [int] NULL,
	[Olympics] [int] NULL,
	[Cascades] [int] NULL,
	[Territorial] [int] NULL,
	[SeattleSkyline] [int] NULL,
	[PugetSound] [int] NULL,
	[LakeWashington] [int] NULL,
	[LakeSammamish] [int] NULL,
	[SmallLakeRiverCreek] [int] NULL,
	[OtherView] [int] NULL,
	[TotalViews] [int] NULL,
	[ViewUtilization] [char](1) NULL,
	[WfntLocation] [int] NULL,
	[WfntFootage] [int] NULL,
	[WfntPoorQuality] [int] NULL,
	[WfntBank] [int] NULL,
	[TidelandShoreland] [int] NULL,
	[WfntRestrictedAccess] [int] NULL,
	[LotDepthFactor] [int] NULL,
	[TrafficNoise] [int] NULL,
	[AirportNoise] [int] NULL,
	[CommonProperty] [int] NULL,
	[CurrentUseDesignation] [int] NULL,
	[HistoricSite] [tinyint] NULL,
	[NbrBldgSites] [int] NULL,
	[Contamination] [int] NULL,
	[WfntAccessRights] [tinyint] NULL,
	[WfntProximityInfluence] [tinyint] NULL,
	[NativeGrowthProtEsmt] [tinyint] NULL,
	[PowerLines] [tinyint] NULL,
	[OtherNuisances] [tinyint] NULL,
	[AdjacentGolfFairway] [tinyint] NULL,
	[AdjacentGreenbelt] [tinyint] NULL,
	[OtherDesignation] [tinyint] NULL,
	[DeedRestrictions] [tinyint] NULL,
	[DevelopmentRightsPurch] [tinyint] NULL,
	[Easements] [tinyint] NULL,
	[SpecialAssessments] [tinyint] NULL,
	[CoalMineHazard] [tinyint] NULL,
	[CriticalDrainage] [tinyint] NULL,
	[ErosionHazard] [tinyint] NULL,
	[LandfillBuffer] [tinyint] NULL,
	[HundredYrFloodPlain] [tinyint] NULL,
	[SeismicHazard] [tinyint] NULL,
	[LandslideHazard] [tinyint] NULL,
	[SteepSlopeHazard] [tinyint] NULL,
	[Stream] [tinyint] NULL,
	[Wetland] [tinyint] NULL,
	[SpeciesOfConcern] [tinyint] NULL,
	[SensitiveAreaTract] [tinyint] NULL,
	[WaterProblems] [tinyint] NULL,
	[OtherProblems] [tinyint] NULL,
	[SrCitFlag] [char](1) NULL,
	[TaxStatus] [char](3) NULL,
	[SegMergeDate] [smalldatetime] NULL,
	[HILastYr] [smallint] NULL,
	[HIValue] [int] NULL,
	[PermitNbr] [varchar](30) NULL,
	[PermitDate] [smalldatetime] NULL,
	[PermitValue] [int] NULL,
	[PermitType] [tinyint] NULL,
	[PermitDescr] [varchar](1024) NULL,
	[Notes] [varchar](Max) NULL,
	--[GovtOwned] [varchar](50) NOT NULL,
	[TrendFactor] [varchar](16) NULL,
	[TrendedPrice] [bigint] NULL,
	[AssignedBoth] [varchar](9) NOT NULL,
	[NewConstrVal] [int] NULL,
	[PIN] [char](10) NULL,
	[MapPin] float   NULL,  	 	
	[AirportValPct] [float] NULL,
	[OtherNuisValPct] [int] NULL,
	[OtherProblemsValPct] [int] NULL,
	[PowerLinesValPct] [int] NULL,
	[RoadAccessValPct] [int] NULL,
	[TopoValPct] [int] NULL,
	[WaterProblemsValPct] [int] NULL,
	[TrafficValPct] [int] NULL,
	[AirportValDollars] [money] NULL,
	[TrafficValDollars] [money] NULL,
	[HundredYrValPct] [int] NULL,
	[CoalValPct] [int] NULL,
	[ContamValPct] [int] NULL,
	[DrainageValPct] [int] NULL,
	[ErosionValPct] [int] NULL,
	[LandfillValPct] [int] NULL,
	[LandslideValPct] [int] NULL,
	[SeismicValPct] [int] NULL,
	[SensitiveValPct] [int] NULL,
	[SpeciesValPct] [int] NULL,
	[SteepSlopeValPct] [int] NULL,
	[StreamValPct] [int] NULL,
	[WetlandValPct] [int] NULL,
	[DevRightsValPct] [int] NULL,
	[AdjacGolfValPct] [int] NULL,
	[AdjacGreenbeltValPct] [int] NULL,
	[DeedRestrictValPct] [int] NULL,
	[EasementsValPct] [int] NULL,
	[DNRLeaseValPct] [int] NULL,
	[NativeGrowthValPct] [int] NULL,
	[OtherDesigValPct] [int] NULL,
	[AdjacGolfDollars] [money] NULL,
	[AdjacGreenbeltValDollars] [money] NULL
 ,PRIMARY KEY(ID)
 ,UNIQUE(ParcelId, ID)
 ,UNIQUE(CurrentZoning, ID)
 ,UNIQUE(ParcelId, BldgGuid, ID)
 ,UNIQUE(LandGuid, ID)
 ,UNIQUE(BldgGrade, ID)
 ,UNIQUE(SaleGuid, ID)
 --,UNIQUE(Condition, BldgGradeCateg, Age, ID)
 ,UNIQUE(FinBasementGrade, ID)
)


--This SP generates all the required data for GetAreaData Custom Search
EXEC [cus].[SRCH_GetAreaData01]  @Area ,@SubArea ,@AssmtYr ,@SalesFrom ,@SalesTo ,@SalePrice ,@Population ,@Notes
		

	IF @Filtered = 'Y'
	BEGIN
		EXEC [cus].[SRCH_GetAreaDataFiltered]  @Area ,@SubArea ,@AssmtYr ,@SalesFrom ,@SalesTo ,@SalePrice ,@Population ,@Notes
	END
	ELSE --Runs like a the regular Custom Search GetAreaData when @Filtered = 'N'
	BEGIN
	  SELECT --,[ParcelId]                    
			 --,[LandGuid]                    
			 --,[SaleGuid]                    
			 --,[BldgGuid]                                       			
			 [Major]                       
			,[Minor]                       
			,[SaleId]  
			,[ResArea]                     
			,[ResSubarea]                  		
			,[PropType]                    
			,[QSec]                        
			,[Sec]                         
			,[Twn]                         
			,[Rng]                         
			,[Neighborhood]                
			,[GisSurfaceValue]             
			,[Folio]                       
			,[PlatLot]                     
			,[PlatBlock]                   
			,[LocationAddr]                
			,[StreetNbr]                   
			,[NbrFraction]                 
			,[DirPrefix]                   
			,[StreetName]                  
			,[StreetType]                  
			,[DirSuffix]                   
			,[DistrictName]                
			,[TaxpayerName]                
			,[SellerName]                  
			,[BuyerName]                   
			,[ExciseTaxNbr]                
			,[SaleYear]                    
			,[SaleMonth]                   
			,[SaleDate]                    
			,[SalePrice]                   
			,[VerifiedAtMkt]               
			,[VerifiedBy]                  
			,[Reason]                      
			,[Instr]                       
			,[PrinUse]                     
			,[PropClass]                   
			,[Warnings]                    
			,[PossibleLenderSale]          
			,[HoldoutReason]               
			,[SelectDate]                  
			,[SelectAppr]                  
			,[SelectMethod]                
			,[SelectReason]                
			,[SelectLandVal]               
			,[SelectImpsVal]               
			,[SelectValTotal]              
			,[RollLandVal]                 
			,[RollImpsVal]                 
			,[RollValTotal]                
			,[BaseLandVal]                 
			,[BaseLandValTaxYr]            
			,[BaseLandValDate]             
			,[BldgRCN]                     
			,[BldgRCNLD]                   
			,[AccyRCN]                     
			,[AccyRCNLD]                   
			,[MHRCN]                       
			,[MHRCNLD]                     
			,[TotalRCN]                    
			,[TotalRCNLD]                  
			,[ImpCnt]                      
			,[BldgNbr]                     
			,[NbrLivingUnits]              
			,[SqFtLot]                     
			,[SqFtLotDry]                  
			,[SqFtLotSubmerged]            
			,[Age]                         
			,[YrBuilt]                     
			,[YrRenovated]                 
			,[BldgGrade]                   
			,[BldgGradeVar]                
			,[Condition]                   
			,[SqFtTotLiving]               
			,[SqFtAboveGrLiving]           
			,[BathTotal]                   
			,[FpTotal]                     
			,[SqFtCoveredParking]          
			,[Stories]                     
			,[SqFt1stFloor]                
			,[SqFtHalfFloor]               
			,[SqFt2ndFloor]                
			,[SqFtUpperFloor]              
			,[SqFtUnfinFull]               
			,[SqFtUnfinHalf]               
			,[SqFtTotBasement]             
			,[SqFtFinBasement]             
			,[FinBasementGrade]            
			,[SqFtGarageBasement]          
			,[SqFtGarageAttached]          
			,[DaylightBasement]            
			,[Bedrooms]                    
			,[BathHalfCount]               
			,[Bath3qtrCount]               
			,[BathFullCount]               
			,[FpSingleStory]               
			,[FpMultiStory]                
			,[FpFreestanding]              
			,[FpAdditional]                
			,[PcntComplete]                
			,[PcntNetCondition]            
			,[Obsolescence]                
			,[SqFtOpenPorch]               
			,[SqFtEnclosedPorch]           
			,[SqFtDeck]                    
			,[HeatSystem]                  
			,[HeatSource]                  
			,[BrickStone]                  
			,[AddnlCost]                   
			,[DetGarArea]                  
			,[DetGarGrade]                 
			,[DetGarEffYr]                 
			,[DetGarNetCond]               
			,[CarportArea]                 
			,[CarportEffYr]                
			,[CarportNetCond]              
			,[PoolArea]                    
			,[PoolEffYr]                   
			,[PoolNetCond]                 
			,[paving]                      
			,[MiscAccyCost]                
			,[DevCost]                     
			,[Flatvalue]                   
			,[MHCount]                     
			,[MHBldgNbr]                   
			,[MHType]                      
			,[MHClass]                     
			,[MHLength]                    
			,[MHWidth]                     
			,[MHLivingArea]                
			,[MHTipOutArea]                
			,[MHRoomAddSqft]               
			,[MHSize]                      
			,[MHYrBuilt]                   
			,[MHCondition]                 
			,[MHPcntNetCondition]          
			,[ZoneClass]                   
			,[CurrentZoning]               
			,[ZoneDesignation]             
			,[ZoningChgDate]               
			,[HBUAsIfVacant]               
			,[HBUasImproved]               
			,[PresentUse]                  
			,[WaterSystem]                 
			,[SewerSystem]                 
			,[Access]                      
			,[Topography]                  
			,[StreetSurface]               
			,[PcntBaseLandValImpacted]     
			,[Unbuildable]                 
			,[RestrictiveSzShape]          
			,[MtRainier]                   
			,[Olympics]                    
			,[Cascades]                    
			,[Territorial]                 
			,[SeattleSkyline]              
			,[PugetSound]                  
			,[LakeWashington]              
			,[LakeSammamish]               
			,[SmallLakeRiverCreek]         
			,[OtherView]                   
			,[TotalViews]                  
			,[ViewUtilization]             
			,[WfntLocation]                
			,[WfntFootage]                 
			,[WfntPoorQuality]             
			,[WfntBank]                    
			,[TidelandShoreland]           
			,[WfntRestrictedAccess]        
			,[LotDepthFactor]              
			,[TrafficNoise]                
			,[AirportNoise]                
			,[CommonProperty]              
			,[CurrentUseDesignation]       
			,[HistoricSite]                
			,[NbrBldgSites]                
			,[Contamination]               
			,[WfntAccessRights]            
			,[WfntProximityInfluence]      
			,[NativeGrowthProtEsmt]        
			,[PowerLines]                  
			,[OtherNuisances]              
			,[AdjacentGolfFairway]         
			,[AdjacentGreenbelt]           
			,[OtherDesignation]            
			,[DeedRestrictions]            
			,[DevelopmentRightsPurch]      
			,[Easements]                   
			,[SpecialAssessments]          
			,[CoalMineHazard]              
			,[CriticalDrainage]            
			,[ErosionHazard]               
			,[LandfillBuffer]              
			,[HundredYrFloodPlain]         
			,[SeismicHazard]               
			,[LandslideHazard]             
			,[SteepSlopeHazard]            
			,[Stream]                      
			,[Wetland]                     
			,[SpeciesOfConcern]            
			,[SensitiveAreaTract]          
			,[WaterProblems]               
			,[OtherProblems]               
			,[SrCitFlag]                   
			,[TaxStatus]                   
			,[SegMergeDate]                
			,[HILastYr]                    
			,[HIValue]                     
			,[PermitNbr]                   
			,[PermitDate]                  
			,[PermitValue]                 
			,[PermitType]                  
			,[PermitDescr]                 
			,[Notes]                       
			--,[GovtOwned]                   
			,[TrendFactor]               
			,[TrendedPrice]                
			,[AssignedBoth]              
			,[NewConstrVal]                
			,[PIN]                         
			,[MapPin]                      
			,[AirportValPct]               
			,[OtherNuisValPct]             
			,[OtherProblemsValPct]         
			,[PowerLinesValPct]            
			,[RoadAccessValPct]            
			,[TopoValPct]                  
			,[WaterProblemsValPct]         
			,[TrafficValPct]               
			,[AirportValDollars]           
			,[TrafficValDollars]           
			,[HundredYrValPct]             
			,[CoalValPct]                  
			,[ContamValPct]                
			,[DrainageValPct]              
			,[ErosionValPct]               
			,[LandfillValPct]              
			,[LandslideValPct]             
			,[SeismicValPct]               
			,[SensitiveValPct]             
			,[SpeciesValPct]               
			,[SteepSlopeValPct]            
			,[StreamValPct]                
			,[WetlandValPct]               
			,[DevRightsValPct]             
			,[AdjacGolfValPct]             
			,[AdjacGreenbeltValPct]        
			,[DeedRestrictValPct]          
			,[EasementsValPct]             
			,[DNRLeaseValPct]              
			,[NativeGrowthValPct]          
			,[OtherDesigValPct]            
			,[AdjacGolfDollars]            
			,[AdjacGreenbeltValDollars]    
			,[ID]
		FROM #SalesPopFinal sp
	   ORDER BY ExciseTaxNbr DESC, ResSubarea, Major, Minor		
	END
END		
		
		
		