
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SRCH_CallGetAreaData')
	DROP PROCEDURE [cus].[SRCH_CallGetAreaData]  
GO

CREATE PROCEDURE [cus].[SRCH_CallGetAreaData]
  @Area		   smallint	= NULL
 ,@SubArea	   smallint	= NULL
 ,@AssmtYr	   smallint	= NULL
 ,@SalesFrom   smalldatetime	= NULL
 ,@SalesTo	   smalldatetime	= NULL
 ,@SalePrice   int		= NULL
 ,@Population  char(3)         = 'N'
 ,@Notes       char(3)         = 'N'
 ,@Filtered	   Char(3) 		   = 'N' -- "N" : runs the search as the regular GetAreaData Search / "Y": Runs the search inclusding the results like the ones generated by the old Macro
		
AS 
BEGIN
/*
Author: Jairo Barquero
Date Created: 01/21/2021
Description:    This SP is used ONLY to call SRCH_GetAreaData to generate the data that use to be in the Excel MACRO
				the only difference between CSs "Get Area" and "Get Area Filtered" is the paramater @Filtered(Y/N)

Modifications:
mm/dd/yyy - [CREATED BY] : [DETAILED DESCRIPTION OF THE CHANGE]
*/
SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC cus.SRCH_GetAreaData  @Area,@SubArea,@AssmtYr,@SalesFrom,@SalesTo,@SalePrice,@Population,@Notes,'Y'	 


END		
		
		
		