module.exports = {
  SUFFIX: {
    JR: "span[aria-label='Jr.']",
    SR: "span[aria-label='Sr.']",
  },
  EXPENSES_DATA: {
    PROVIDER: 'span[aria-label="United Healthcare"]',
    PLAN: 'li[data-value="07f6d35c-3d94-e911-a979-001dd800d601"]',
  },
  SIGN_IN: {
    GOOGLE_LOGIN:
      'https://accounts.google.com/signin/v2/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&service=mail&sacu=1&rip=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin',
    OUTLOOK_LOGIN: 'https://outlook.live.com/owa/',
  },
  MY_INFO: {
    FIRST_NAME: 'Anne',
    MIDDLE_NAME: 'Verena',
    LAST_NAME: 'Miller',
    SUFFIX: 'Jr.',
    DATE_OF_BIRTH: '10/21/1947',
    EMAIL: 'katsumikitamura@outlook.com',
    PASSWORD: 'SPMjgGvJHuN7Spz4eJLC',
    PHONE: 1111111111,
    PHONE_TEST: '111-111-1111',
    PARTNER: {
      FIRST_NAME: 'Stephanie',
      MIDDLE_NAME: 'Leona',
      LAST_NAME: 'Apple',
      SUFFIX: 'Jr.',
      DATE_OF_BIRTH: '12/24/1941',
    },
    WITNESS1: 'Cielo Nublado',
    WITNESS2: 'Noche Solar',
  },
  PROPERTY: {
    MY_ADDRESS: '123',
    ADDRESS: 'KENT, WA ',
    ACQUIRED_DATE: "10/21/2000'",
    FIRST_DATE: '2000',
    OTHER_ADDRESS1: '686',
    OTHER_PURPOSE: {
      RENTAL: "span[aria-label='Rental']",
      SECONDARY: "span[aria-label='Secondary']",
      OTHER: "span[aria-label='Other']",
    },
    PARTNER: {
      FIRST_NAME: 'John',
      MIDDLE_NAME: 'Malone',
      LAST_NAME: 'Doe',
      SUFFIX: 'Sr.',
      RELATIONSHIP: '668020001',
      EXPENSES: {
        ASSISTED_LIVING: '10.00',
        IN_HOME_CARE: '20.00',
        NON_REIMBURSED_PRESCRIPTIONS: '30.00',
        APPROVED_MEDICARE: '40.00',
        MEDIACARE_PROVIDER: 'United Healthcare',
        MEDICAL_PLAN: '07f6d35c-3d94-e911-a979-001dd800d601',
        EXPENSES_DATA: {
          PROVIDER: 'li[data-value="United Healthcare"]',
          PLAN: 'li[data-value="07f6d35c-3d94-e911-a979-001dd800d601"]',
        },
      },
    },
    COOP: {
      NAME: 'Katja Schuster',
      TREASURER: 'Maximilian Mauer',
      TREASURER_PHONE: '1111111111',
      TREASURER_PHONE_TEST: '111-111-1111',
      NUMBER_OF_SHARES: '100',
      TOTAL_SHARES: '200',
    },
    PREVIOUS_FIRST_DATE: '10/21/2007',
    PREVIOUS_COUNTY: '077e61dd-3c94-e911-a97b-001dd800d878',
    PREVIOUS_ADDRESS: '989',
    PREVIOUS_PARCEL_NUM: '4100',
    PREVIOUS_ZIP: '4010',
    OTHER_ADDRESS: {
      FULL_NAME: 'My adress full name',
      COUNTRY: 'b850ac6e-60b4-e911-a980-001dd800cc2e',
      MAILING_ADDRESS: 'My mailing address',
      CITY: 'Ellensburg',
      STATE: 'WA',
      ZIP: '98660',
    },
    CHECK_ADDRESS: {
      FULL_NAME: 'MOON ELIZABETH',
      ADDRESS: '77840',
      COUNTRY: "span[aria-label='United States']",
      MAILING_ADDRESS: 'College Station, Texas 77840, United States',
      CITY: 'College Station',
      STATE: 'TX',
      ZIP: '98103',
    },
  },
  EXPENSES: {
    ASSISTED_LIVING: '100',
    IN_HOME_CARE: '200',
    NON_REIMBURSED_PRESCRIPTIONS: '300',
    APPROVED_MEDICARE: '400',
    MEDIACARE_PROVIDER: 'Aetna Medicare',
    MEDICAL_PLAN: 'Aetna Medicare Platinum Plan',
    EXPENSES_DATA: {
      PROVIDER: "span[aria-label='Aetna Medicare']",
      PLAN: "span[aria-label='Aetna Medicare Platinum Plan']",
    },
  },
  EXPENSES2: {
    ASSISTED_LIVING: '78',
    IN_HOME_CARE: '97',
    NON_REIMBURSED_PRESCRIPTIONS: '55',
    APPROVED_MEDICARE: '52',
    MEDIACARE_PROVIDER: 'United Healthcare',
    MEDICAL_PLAN: 'United Healthcare Dual Complete',
    EXPENSES_DATA: {
      PROVIDER: "span[aria-label='United Healthcare']",
      PLAN: "span[aria-label='United Healthcare Dual Complete']",
    },
  },
  FINANCES: {
    FORM: {
      NET_SOCIAL_SECURITY_LESS_MEDIACARE: '10',
      INTEREST_DIVIDENDS: '15',
      PENSIONS_AND_ANNUITIES: '60',
      IRAS: '55',
      WAGES: '10',
      CAPITAL_GAINS: '45',
      BUSINESS_INCOME: '40',
      OTHER_GAINS: '50',
      RENTAL: '70',
      GIFTS: '20',
      INCOME_FROM_OTHER_COUNTRIES: '30',
      EXPENSES_PAID_BY_FAMILY_OR_FRIENDS: '35',
      UNEMPLOYMENT: '80',
      PUBLIC_ASSISTANCE: '40',
      GAMBLING: '50',
      DISABILITY_INCOME: '60',
      VA_BENEFIT: '70',
      DISABILITY_SOURCE: {
        SOCIAL_SECURITY: "span[aria-label='Social Security']",
        LABOR_AND_INDUSTRIES: "span[aria-label='Labor & Industries']",
        PRIVATE_INSURANCE: "span[aria-label='Private Insurance']",
      },
      DISABILITY_SOURCE_TEST: {
        SOCIAL_SECURITY: 'Social Security',
        LABOR_AND_INDUSTRIES: 'Labor & Industries',
        PRIVATE_INSURANCE: 'Private Insurance',
      },
      ROYAL_INCOME: '100',
      BONDS_INCOME: '110',
      ALIMONY: '35',
    },
    FORM2: {
      NET_SOCIAL_SECURITY_LESS_MEDIACARE: '50',
      INTEREST_DIVIDENDS: '30',
      PENSIONS_AND_ANNUITIES: '10',
      IRAS: '12',
      WAGES: '77',
      CAPITAL_GAINS: '88',
      BUSINESS_INCOME: '66',
      OTHER_GAINS: '88',
      RENTAL: '97',
      GIFTS: '12',
      INCOME_FROM_OTHER_COUNTRIES: '31',
      EXPENSES_PAID_BY_FAMILY_OR_FRIENDS: '357',
      UNEMPLOYMENT: '55',
      PUBLIC_ASSISTANCE: '555',
      GAMBLING: '78',
      DISABILITY_INCOME: '97',
      VA_BENEFIT: '100',
      DISABILITY_SOURCE: {
        SOCIAL_SECURITY: "span[aria-label='Social Security']",
        LABOR_AND_INDUSTRIES: "span[aria-label='Labor & Industries']",
        PRIVATE_INSURANCE: "span[aria-label='Private Insurance']",
      },
      DISABILITY_SOURCE_TEST: {
        SOCIAL_SECURITY: 'Social Security',
        LABOR_AND_INDUSTRIES: 'Labor & Industries',
        PRIVATE_INSURANCE: 'Private Insurance',
      },
      ROYAL_INCOME: '100',
      BONDS_INCOME: '110',
      ALIMONY: '35',
    },
  },
  TEST: {
    CURRENCY: '$',
    METRIC: ' square feet',
    DECIMAL: '.00',
    PROPERTY: {
      FULL_NAME: 'CHAI JAY C+SOOHYUN',
      MAILING_ADDRESS: '8211  125TH NE',
      CITY: 'KIRKLAND',
      STATE: 'WA',
      ZIP: '98033',
      ADDRESS: 'KIRKLAND, WA 98033',
      OTHER_ADDRESS: '68601, Columbus, Nebraska,  Columbus',
      PREVIOUS_ADDRESS: 'Ellensburg, Washington 98926, United States',
      PREVIOUS_CITY: 'Ellensburg',
      PREVIOUS_STATE: 'WA',
      PREVIOUS_ZIP: '98660',
      OTHER_PURPOSE: {
        RENTAL: 'Rental',
        SECONDARY: 'Secondary',
        OTHER: 'Other',
      },
    },
  },
};
