// <copyright file="MyConfig.cs" company="King County">
//  Copyright (c) King County. All rights reserved.
// </copyright>
// <auto-generated />

namespace PTASDynamicsTranfer
{
    using System.Collections.Generic;

    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.Primitives;

    using Newtonsoft.Json;

    public class MyConfig : IConfigurationRoot
    {
        private readonly IConfigurationRoot baseObject;
        private readonly Dictionary<string, string> options;

        public MyConfig(IConfigurationRoot baseObject, Options options)
        {
            this.options = JsonConvert.DeserializeObject<Dictionary<string, string>>(JsonConvert.SerializeObject(options));
            this.baseObject = baseObject;
        }

        public IEnumerable<IConfigurationProvider> Providers => this.baseObject.Providers;

        public string this[string key]
        {
            get
            {
                if (this.options.TryGetValue(key, out string result))
                {
                    return result;
                }

                return this.baseObject[key];
            }

            set
            {
                this.baseObject[key] = value;
            }
        }

        public IEnumerable<IConfigurationSection> GetChildren() => this.baseObject.GetChildren();

        public IChangeToken GetReloadToken() => this.baseObject.GetReloadToken();

        public IConfigurationSection GetSection(string key)
        {
            return new MyConnectionStringSection(this.baseObject.GetSection(key), this.options["ConnectionString"]);
        }

        public void Reload() => this.baseObject.Reload();
    }
}