// <copyright file="MyConnectionStringSection.cs" company="King County">
//  Copyright (c) King County. All rights reserved.
// </copyright>
// <auto-generated />

namespace PTASDynamicsTranfer
{
    using System.Collections.Generic;

    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.Primitives;

    public class MyConnectionStringSection : IConfigurationSection
    {
        private readonly IConfigurationSection configurationSection;
        private readonly string connectionString;

        public MyConnectionStringSection(IConfigurationSection configurationSection, string connectionString)
        {
            this.connectionString = connectionString;
            this.configurationSection = configurationSection;
        }

        public string Key => this.configurationSection.Key;

        public string Path => this.configurationSection.Path;

        public string Value { get => this.configurationSection.Value; set => this.configurationSection.Value = value; }

        public string this[string key]
        {
            get
            {
                return key == "default" ? this.connectionString : this.configurationSection[key];
            }

            set => this.configurationSection[key] = value;
        }

        public IEnumerable<IConfigurationSection> GetChildren()
        {
            return this.configurationSection.GetChildren();
        }

        public IChangeToken GetReloadToken() => this.configurationSection.GetReloadToken();

        public IConfigurationSection GetSection(string key)
        {
            return this.configurationSection.GetSection(key);
        }
    }
}