namespace PTASMapTileServicesLibrary.TileProvider.Exception
{
    using System;

    /// <summary>
    /// Exception generated by the tile provider.
    /// </summary>
    /// <seealso cref="System.Exception" />
    public class TileProviderException : System.Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TileProviderException" /> class.
        /// </summary>
        /// <param name="exceptionCategory">Category of the exception.</param>
        /// <param name="tileProviderType">Type of the tile provider that generated the exception.</param>
        /// <param name="message">The exception message.</param>
        /// <param name="innerException">The inner exception.</param>
        /// <exception cref="System.ArgumentNullException">When tileProviderType is null.</exception>
        public TileProviderException(TileProviderExceptionCategory exceptionCategory, Type tileProviderType, string message, System.Exception innerException)
            : base(message, innerException)
        {
            if (tileProviderType == null)
            {
                throw new ArgumentNullException(nameof(tileProviderType));
            }

            this.TileProviderExceptionCategory = exceptionCategory;
            this.TileProviderType = tileProviderType;
        }

        /// <summary>
        /// Gets the category of the tile exception.
        /// </summary>
        public TileProviderExceptionCategory TileProviderExceptionCategory { get; }

        /// <summary>
        /// Gets the type of the tile provider that generated the exception.
        /// </summary>
        public Type TileProviderType { get; }
    }
}