IF EXISTS (SELECT * FROM sys.objects WHERE type = 'V' AND name = 'vw_ResBldg')
    DROP VIEW dynamics.vw_ResBldg;  
GO 

CREATE VIEW dynamics.vw_ResBldg
WITH SCHEMABINDING
AS
/*
Author: Jairo Barquero
Date Created:  10/11/2020
Description:    This View returns all residential buildings

Modifications:
mm/dd/yyy - [CREATED BY] : [DETAILED DESCRIPTION OF THE CHANGE]
*/

SELECT bd.[ptas_buildingdetailid]
      ,bd.[createdon]
      ,bd.[exchangerate]
      ,bd.[importsequencenumber]
      ,bd.[modifiedon]
      ,bd.[overriddencreatedon]
      ,bd.[ptas_12baths]
      ,bd.[ptas_1stflr_sqft]
      ,bd.[ptas_2ndflr_sqft]
      ,bd.[ptas_34baths]
      ,bd.[ptas_additionalcost]
      ,bd.[ptas_additionalcost_base]
      ,bd.[ptas_additionallivingquarters]
      ,bd.[ptas_addl_fireplace]
      ,bd.[ptas_addr1_compositeaddress]
      ,bd.[ptas_addr1_compositeaddress_oneline]
      ,bd.[ptas_addr1_directionprefix]
      ,bd.[ptas_addr1_directionsuffix]
      ,bd.[ptas_addr1_line2]
      ,bd.[ptas_addr1_streetnumber]
      ,bd.[ptas_addr1_streetnumberfraction]
      ,bd.[ptas_alternatekey]
      ,bd.[ptas_attachedgarage_sqft]
      ,bd.[ptas_basementgarage_sqft]
      ,bd.[ptas_bedroomnbr]
      ,bd.[ptas_buildingdescription]
      ,bd.[ptas_buildinggrade]
      ,bd.[ptas_buildinggross_sqft]
      ,bd.[ptas_buildingnbr]
      ,bd.[ptas_buildingnet_sqft]
      ,bd.[ptas_buildingnumber]
      ,bd.[ptas_buildingobsolescence]
      ,bd.[ptas_buildingquality]
      ,bd.[ptas_builtgreen]
      ,bd.[ptas_clearheightft]
      ,bd.[ptas_commercialheatingsystem]
      ,bd.[ptas_constructionclass]
      ,bd.[ptas_cranecapacity]
      ,bd.[ptas_craneloading]
      ,bd.[ptas_daylightbasement]
      ,bd.[ptas_deck_sqft]
      ,bd.[ptas_directnavigation]
      ,bd.[ptas_dockloading]
      ,bd.[ptas_elevators]
      ,bd.[ptas_enclosedporch_sqft]
      ,bd.[ptas_energyrating]
      ,bd.[ptas_finbsmt_sqft]
      ,bd.[ptas_fr_std_fireplace]
      ,bd.[ptas_fullbathnbr]
      ,bd.[ptas_fullsitusaddress]
      ,bd.[ptas_gradevariance]
      ,bd.[ptas_halfflr_sqft]
      ,bd.[ptas_heatingsystem]
      ,bd.[ptas_invertedfloorplan]
      ,bd.[ptas_leasingclass]
      ,bd.[ptas_legacycreatedby]
      ,bd.[ptas_legacycreatedon]
      ,bd.[ptas_legacymodifiedby]
      ,bd.[ptas_legacymodifiedon]
      ,bd.[ptas_multi_fireplace]
      ,bd.[ptas_name]
      ,bd.[ptas_numberofaggregate]
      ,bd.[ptas_numberofbuildings]
      ,bd.[ptas_numberofcommonwalls]
      ,bd.[ptas_numberofelevators]
      ,bd.[ptas_numberofstories]
      ,bd.[ptas_numberofstoriesdecimal]
      ,bd.[ptas_onsiteparking]
      ,bd.[ptas_openporch_sqft]
      ,bd.[ptas_parcelheadername]
      ,bd.[ptas_parcelheadertext]
      ,bd.[ptas_parcelheadertext2]
      ,bd.[ptas_percentbrickorstone]
      ,bd.[ptas_percentcomplete]
      ,bd.[ptas_percentnetcondition]
      ,bd.[ptas_res_basementgrade]
      ,bd.[ptas_res_buildingcondition]
      ,bd.[ptas_res_heatsource]
      ,bd.[ptas_residentialheatingsystem]
      ,bd.[ptas_restored]
      ,bd.[ptas_rooftopdeck]
      ,bd.[ptas_shape]
      ,bd.[ptas_showrecordchanges]
      ,bd.[ptas_single_fireplace]
      ,bd.[ptas_situsaddress]
      ,bd.[ptas_slabthickness]
      ,bd.[ptas_snapshotdatetime]
      ,bd.[ptas_snapshottype]
      ,bd.[ptas_solarpanels]
      ,bd.[ptas_specialtyarea]
      ,bd.[ptas_specialtyneighborhood]
      ,bd.[ptas_sprinklers]
      ,bd.[ptas_style]
      ,bd.[ptas_totalbsmt_sqft]
      ,bd.[ptas_totalliving_sqft]
      ,bd.[ptas_townhouse]
      ,bd.[ptas_unfinished_full_sqft]
      ,bd.[ptas_unfinished_half_sqft]
      ,bd.[ptas_unitdescription]
      ,bd.[ptas_units]
      ,bd.[ptas_upperflr_sqft]
      ,bd.[ptas_viewutilizationrating]
      ,bd.[statecode]
      ,bd.[statuscode]
      ,bd.[timezoneruleversionnumber]
      ,bd.[utcconversiontimezonecode]
      ,bd.[versionnumber]
      ,bd.[_createdby_value]
      ,bd.[_createdonbehalfby_value]
      ,bd.[_modifiedby_value]
      ,bd.[_modifiedonbehalfby_value]
      ,bd.[_ownerid_value]
      ,bd.[_owningbusinessunit_value]
      ,bd.[_owningteam_value]
      ,bd.[_owninguser_value]
      ,bd.[_ptas_addr1_cityid_value]
      ,bd.[_ptas_addr1_countryid_value]
      ,bd.[_ptas_addr1_stateid_value]
      ,bd.[_ptas_addr1_streetnameid_value]
      ,bd.[_ptas_addr1_streettypeid_value]
      ,bd.[_ptas_addr1_zipcodeid_value]
      ,bd.[_ptas_buildingsectionuseid_value]
      ,bd.[_ptas_effectiveyearid_value]
      ,bd.[_ptas_heatingsystemid_value]
      ,bd.[_ptas_masterbuildingid_value]
      ,bd.[_ptas_parceldetailid_value]
      ,bd.[_ptas_propertytypeid_value]
      ,bd.[_ptas_sketchid_value]
      ,bd.[_ptas_specialtyareaid_value]
      ,bd.[_ptas_specialtynbhdid_value]
      ,bd.[_ptas_yearbuiltid_value]
      ,bd.[_ptas_yearrenovatedid_value]
      ,bd.[_transactioncurrencyid_value]
FROM [dynamics].[ptas_buildingdetail] bd 
INNER JOIN [dynamics].[ptas_propertytype] dpt
   ON bd._ptas_propertytypeid_value = dpt.ptas_propertytypeid
  AND dpt.ptas_description = 'Residential'