namespace CustomSearchesServicesLibrary.Exception
{
    using System;

    /// <summary>
    /// Exception generated by an unauthorized action.
    /// </summary>
    /// <seealso cref="Exception" />
    public class AuthorizationException : Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizationException" /> class.
        /// </summary>
        /// <param name="message">The exception message.</param>
        /// <param name="innerException">The inner exception.</param>
        public AuthorizationException(string message, Exception innerException)
            : base(message, innerException)
        {
        }
    }
}