namespace CustomSearchesServicesLibrary.Exception
{
    using System;

    /// <summary>
    /// Exception generated by the deserialization of the request body.
    /// </summary>
    /// <seealso cref="System.Exception" />
    public class CustomSearchesRequestBodyException : System.Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomSearchesRequestBodyException" /> class.
        /// </summary>
        /// <param name="message">The exception message.</param>
        /// <param name="innerException">The inner exception.</param>
        public CustomSearchesRequestBodyException(string message, System.Exception innerException)
            : base(message, innerException)
        {
        }
    }
}