namespace CustomSearchesServicesLibrary.Exception
{
    using CustomSearchesServicesLibrary.Enumeration;

    /// <summary>
    /// Represents errors generated by the folder manager.
    /// </summary>
    /// <seealso cref="System.Exception" />
    public class FolderManagerException : System.Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FolderManagerException" /> class.
        /// </summary>
        /// <param name="message">The exception message.</param>
        /// <param name="folderManagerExceptionType">The folder manager exception type.</param>
        /// <param name="innerException">The inner exception.</param>
        public FolderManagerException(string message, FolderManagerExceptionType folderManagerExceptionType, System.Exception innerException)
            : base(message, innerException)
        {
            this.FolderManagerExceptionType = folderManagerExceptionType;
        }

        /// <summary>
        /// Gets or sets the folder manager exception type.
        /// </summary>
        public FolderManagerExceptionType FolderManagerExceptionType { get; set; }
    }
}