// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "CustomSearchesValuationEFLibrary.Model")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "CustomSearchesValuationEFLibrary.Model")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "CustomSearchesValuationEFLibrary.Model")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1512:Single-line comments should not be followed by blank line", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "CustomSearchesValuationEFLibrary.Model")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "AutoGenerated Files", Scope = "namespaceanddescendants", Target = "CustomSearchesValuationEFLibrary.Model")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1210:Using directives should be ordered alphabetically by namespace", Justification = "AutoGenerated Files")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1200:Using directives should be placed correctly", Justification = "AutoGenerated Files")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "AutoGenerated Files", Scope = "type", Target = "~T:CustomSearchesValuationEFLibrary.ValuationDbContext")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1512:Single-line comments should not be followed by blank line", Justification = "AutoGenerated Files", Scope = "namespace", Target = "~N:CustomSearchesValuationEFLibrary")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "AutoGenerated Files", Scope = "type", Target = "~T:CustomSearchesValuationEFLibrary.ValuationDbContext")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "AutoGenerated Files", Scope = "type", Target = "~T:CustomSearchesValuationEFLibrary.ValuationDbContext")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "AutoGenerated Files", Scope = "type", Target = "~T:CustomSearchesValuationEFLibrary.ValuationDbContext")]