// <copyright file="DynamicsInterfaceException.cs" company="King County">
//  Copyright (c) King County. All rights reserved.
// </copyright>

namespace PTASDynamicsCrudHelperClasses.Exception
{
    using System;

    /// <summary>
    /// Model for error generated by Http request.
    /// </summary>
    public class DynamicsInterfaceException : Exception
    {
        private const string HeaderLog = "API Web Dynamics Interface: ";

        /// <summary>
        /// Initializes a new instance of the <see cref="DynamicsInterfaceException"/> class.
        /// Model for throwing error from CrmODatahelper class.
        /// </summary>
        /// <param name="message"> the error message generated inside CRMWrapper class.</param>
        /// <param name="statusCode"> Status code of the error to be propagated to outside.</param>
        /// <param name="innerException"> The exception that comes from inner code.</param>
        public DynamicsInterfaceException(string message, int statusCode, Exception innerException)
            : base(message, innerException)
        {
            this.StatusCode = statusCode;
        }

        /// <summary>
        /// Gets the error status code.
        /// </summary>
        public int StatusCode { get; }
    }
}
