using System;
using System.Collections.Generic;

namespace PTASODataLibrary.PtasDbDataProvider.PtasCamaModel
{
    public partial class PtasSefinancialforms
    {
        public Guid PtasSefinancialformsid { get; set; }
        public DateTimeOffset? Createdon { get; set; }
        public decimal? Exchangerate { get; set; }
        public int? Importsequencenumber { get; set; }
        public DateTimeOffset? Modifiedon { get; set; }
        public DateTimeOffset? Overriddencreatedon { get; set; }
        public decimal? Ptas10402017alimonyrcvd { get; set; }
        public decimal? Ptas10402017alimonyrcvdBase { get; set; }
        public decimal? Ptas10402017bizincomeorloss { get; set; }
        public decimal? Ptas10402017bizincomeorlossBase { get; set; }
        public decimal? Ptas10402017capgainloss { get; set; }
        public decimal? Ptas10402017capgainlossBase { get; set; }
        public decimal? Ptas10402017deductions { get; set; }
        public decimal? Ptas10402017deductionsBase { get; set; }
        public decimal? Ptas10402017dividends { get; set; }
        public decimal? Ptas10402017dividendsBase { get; set; }
        public decimal? Ptas10402017farmincomeloss { get; set; }
        public decimal? Ptas10402017farmincomelossBase { get; set; }
        public decimal? Ptas10402017iradisttax { get; set; }
        public decimal? Ptas10402017iradisttaxBase { get; set; }
        public decimal? Ptas10402017othergainsloss { get; set; }
        public decimal? Ptas10402017othergainslossBase { get; set; }
        public decimal? Ptas10402017otherincome { get; set; }
        public decimal? Ptas10402017otherincomeBase { get; set; }
        public string Ptas10402017otherincometype { get; set; }
        public decimal? Ptas10402017penannuitiestax { get; set; }
        public decimal? Ptas10402017penannuitiestaxBase { get; set; }
        public decimal? Ptas10402017pensionsannuties { get; set; }
        public decimal? Ptas10402017pensionsannutiesBase { get; set; }
        public decimal? Ptas10402017royaltiestrustsetc { get; set; }
        public decimal? Ptas10402017royaltiestrustsetcBase { get; set; }
        public decimal? Ptas10402017ssbenefits { get; set; }
        public decimal? Ptas10402017ssbenefitsBase { get; set; }
        public decimal? Ptas10402017taxexinterest { get; set; }
        public decimal? Ptas10402017taxexinterestBase { get; set; }
        public decimal? Ptas10402017taxinterest { get; set; }
        public decimal? Ptas10402017taxinterestBase { get; set; }
        public decimal? Ptas10402017taxrefunds { get; set; }
        public decimal? Ptas10402017taxrefundsBase { get; set; }
        public decimal? Ptas10402017unemployment { get; set; }
        public decimal? Ptas10402017unemploymentBase { get; set; }
        public decimal? Ptas10402017wages { get; set; }
        public decimal? Ptas10402017wagesBase { get; set; }
        public decimal? Ptas10402018adjgrossincome { get; set; }
        public decimal? Ptas10402018adjgrossincomeBase { get; set; }
        public decimal? Ptas10402018dividends { get; set; }
        public decimal? Ptas10402018dividendsBase { get; set; }
        public decimal? Ptas10402018irapensions { get; set; }
        public decimal? Ptas10402018irapensionsBase { get; set; }
        public decimal? Ptas10402018irapensionstax { get; set; }
        public decimal? Ptas10402018irapensionstaxBase { get; set; }
        public decimal? Ptas10402018ssbenefits { get; set; }
        public decimal? Ptas10402018ssbenefitsBase { get; set; }
        public decimal? Ptas10402018taxexinterest { get; set; }
        public decimal? Ptas10402018taxexinterestBase { get; set; }
        public decimal? Ptas10402018taxinterest { get; set; }
        public decimal? Ptas10402018taxinterestBase { get; set; }
        public decimal? Ptas10402018totalincome { get; set; }
        public decimal? Ptas10402018totalincomeBase { get; set; }
        public decimal? Ptas10402018wages { get; set; }
        public decimal? Ptas10402018wagesBase { get; set; }
        public decimal? Ptas1040acapgains { get; set; }
        public decimal? Ptas1040acapgainsBase { get; set; }
        public decimal? Ptas1040adeductions { get; set; }
        public decimal? Ptas1040adeductionsBase { get; set; }
        public decimal? Ptas1040airadisttax { get; set; }
        public decimal? Ptas1040airadisttaxBase { get; set; }
        public decimal? Ptas1040aorddividends { get; set; }
        public decimal? Ptas1040aorddividendsBase { get; set; }
        public decimal? Ptas1040apensions { get; set; }
        public decimal? Ptas1040apensionsBase { get; set; }
        public decimal? Ptas1040apensionstax { get; set; }
        public decimal? Ptas1040apensionstaxBase { get; set; }
        public decimal? Ptas1040asocialsec { get; set; }
        public decimal? Ptas1040asocialsecBase { get; set; }
        public decimal? Ptas1040ataxexinterest { get; set; }
        public decimal? Ptas1040ataxexinterestBase { get; set; }
        public decimal? Ptas1040ataxinterest { get; set; }
        public decimal? Ptas1040ataxinterestBase { get; set; }
        public decimal? Ptas1040ataxrefunds { get; set; }
        public decimal? Ptas1040ataxrefundsBase { get; set; }
        public decimal? Ptas1040aunemployment { get; set; }
        public decimal? Ptas1040aunemploymentBase { get; set; }
        public decimal? Ptas1040awages { get; set; }
        public decimal? Ptas1040awagesBase { get; set; }
        public decimal? Ptas1040eztaxinterest { get; set; }
        public decimal? Ptas1040eztaxinterestBase { get; set; }
        public decimal? Ptas1040ezunemployment { get; set; }
        public decimal? Ptas1040ezunemploymentBase { get; set; }
        public decimal? Ptas1040ezwages { get; set; }
        public decimal? Ptas1040ezwagesBase { get; set; }
        public int? Ptas8829percentusedforbusiness { get; set; }
        public decimal? Ptas8949totalgains { get; set; }
        public decimal? Ptas8949totalgainsBase { get; set; }
        public int? PtasAlternatekey { get; set; }
        public int? PtasAlternatekey2 { get; set; }
        public bool? PtasExcludefromtotal { get; set; }
        public decimal? PtasExpenseassistedliving { get; set; }
        public decimal? PtasExpenseassistedlivingBase { get; set; }
        public string PtasExpenseassistedlivingpayee { get; set; }
        public string PtasExpenseinhomepayee { get; set; }
        public decimal? PtasExpensemedicareplan { get; set; }
        public decimal? PtasExpensemedicareplanBase { get; set; }
        public decimal? PtasExpensenursinghome { get; set; }
        public decimal? PtasExpensenursinghomeBase { get; set; }
        public string PtasExpensenursingpayee { get; set; }
        public decimal? PtasExpenseother { get; set; }
        public decimal? PtasExpenseotherBase { get; set; }
        public decimal? PtasExpensepres { get; set; }
        public decimal? PtasExpensepresBase { get; set; }
        public decimal? PtasExpensesinhome { get; set; }
        public decimal? PtasExpensesinhomeBase { get; set; }
        public int? PtasFilertype { get; set; }
        public int? PtasFinancialformtype { get; set; }
        public decimal? PtasIncomealimony { get; set; }
        public decimal? PtasIncomealimonyBase { get; set; }
        public decimal? PtasIncomebusiness { get; set; }
        public decimal? PtasIncomebusinessBase { get; set; }
        public decimal? PtasIncomecapgains { get; set; }
        public decimal? PtasIncomecapgainsBase { get; set; }
        public decimal? PtasIncomecoowner { get; set; }
        public decimal? PtasIncomecoownerBase { get; set; }
        public decimal? PtasIncomecountries { get; set; }
        public decimal? PtasIncomecountriesBase { get; set; }
        public decimal? PtasIncomedisability { get; set; }
        public decimal? PtasIncomedisabilityBase { get; set; }
        public int? PtasIncomedisabilitysrc { get; set; }
        public decimal? PtasIncomedividends { get; set; }
        public decimal? PtasIncomedividendsBase { get; set; }
        public decimal? PtasIncomedshs { get; set; }
        public decimal? PtasIncomedshsBase { get; set; }
        public decimal? PtasIncomeexpenses { get; set; }
        public decimal? PtasIncomeexpensesBase { get; set; }
        public decimal? PtasIncomegambling { get; set; }
        public decimal? PtasIncomegamblingBase { get; set; }
        public decimal? PtasIncomegifts { get; set; }
        public decimal? PtasIncomegiftsBase { get; set; }
        public decimal? PtasIncomeirataxamt { get; set; }
        public decimal? PtasIncomeirataxamtBase { get; set; }
        public decimal? PtasIncomeother { get; set; }
        public decimal? PtasIncomeotherBase { get; set; }
        public decimal? PtasIncomerental { get; set; }
        public decimal? PtasIncomerentalBase { get; set; }
        public decimal? PtasIncomeretirement { get; set; }
        public decimal? PtasIncomeretirementBase { get; set; }
        public decimal? PtasIncomeschedeother { get; set; }
        public decimal? PtasIncomeschedeotherBase { get; set; }
        public decimal? PtasIncomeservicedisability { get; set; }
        public decimal? PtasIncomeservicedisabilityBase { get; set; }
        public decimal? PtasIncomesocialsec { get; set; }
        public decimal? PtasIncomesocialsecBase { get; set; }
        public decimal? PtasIncomeunemployment { get; set; }
        public decimal? PtasIncomeunemploymentBase { get; set; }
        public decimal? PtasIncomewages { get; set; }
        public decimal? PtasIncomewagesBase { get; set; }
        public string PtasLegacycreatedby { get; set; }
        public DateTimeOffset? PtasLegacycreatedon { get; set; }
        public string PtasLegacymodifiedby { get; set; }
        public DateTimeOffset? PtasLegacymodifiedon { get; set; }
        public string PtasName { get; set; }
        public decimal? PtasNettotalincome { get; set; }
        public decimal? PtasNettotalincomeBase { get; set; }
        public DateTimeOffset? PtasReviewedon { get; set; }
        public int? PtasReviewstatus { get; set; }
        public decimal? PtasSchd1alimony { get; set; }
        public decimal? PtasSchd1alimonyBase { get; set; }
        public decimal? PtasSchd1businessincomeloss { get; set; }
        public decimal? PtasSchd1businessincomelossBase { get; set; }
        public decimal? PtasSchd1capgainloss { get; set; }
        public decimal? PtasSchd1capgainlossBase { get; set; }
        public decimal? PtasSchd1farmincomeloss { get; set; }
        public decimal? PtasSchd1farmincomelossBase { get; set; }
        public decimal? PtasSchd1othergainsloss { get; set; }
        public decimal? PtasSchd1othergainslossBase { get; set; }
        public decimal? PtasSchd1otherincomeamt { get; set; }
        public decimal? PtasSchd1otherincomeamtBase { get; set; }
        public string PtasSchd1otherincometype { get; set; }
        public decimal? PtasSchd1rentalrealestate { get; set; }
        public decimal? PtasSchd1rentalrealestateBase { get; set; }
        public decimal? PtasSchd1taxrefunds { get; set; }
        public decimal? PtasSchd1taxrefundsBase { get; set; }
        public decimal? PtasSchd1unemployment { get; set; }
        public decimal? PtasSchd1unemploymentBase { get; set; }
        public decimal? PtasSchdcdepreciation { get; set; }
        public decimal? PtasSchdcdepreciationBase { get; set; }
        public decimal? PtasSchdcexbusinesshome { get; set; }
        public decimal? PtasSchdcexbusinesshomeBase { get; set; }
        public decimal? PtasSchdcnetprofitloss { get; set; }
        public decimal? PtasSchdcnetprofitlossBase { get; set; }
        public decimal? PtasSchdcotherincomeamt { get; set; }
        public decimal? PtasSchdcotherincomeamtBase { get; set; }
        public int? PtasSchdcsqftbusiness { get; set; }
        public int? PtasSchdcsqfthome { get; set; }
        public decimal? PtasSchddcapgains { get; set; }
        public decimal? PtasSchddcapgainsBase { get; set; }
        public decimal? PtasSchddlongtermboxa { get; set; }
        public decimal? PtasSchddlongtermboxaBase { get; set; }
        public decimal? PtasSchddlongtermboxb { get; set; }
        public decimal? PtasSchddlongtermboxbBase { get; set; }
        public decimal? PtasSchddlongtermboxc { get; set; }
        public decimal? PtasSchddlongtermboxcBase { get; set; }
        public decimal? PtasSchddnetshorttermgains { get; set; }
        public decimal? PtasSchddnetshorttermgainsBase { get; set; }
        public bool? PtasSchddrequired { get; set; }
        public decimal? PtasSchddshortterm6252 { get; set; }
        public decimal? PtasSchddshortterm6252Base { get; set; }
        public decimal? PtasSchddshorttermboxa { get; set; }
        public decimal? PtasSchddshorttermboxaBase { get; set; }
        public decimal? PtasSchddshorttermboxb { get; set; }
        public decimal? PtasSchddshorttermboxbBase { get; set; }
        public decimal? PtasSchddshorttermboxc { get; set; }
        public decimal? PtasSchddshorttermboxcBase { get; set; }
        public decimal? PtasSchdedepreciation { get; set; }
        public decimal? PtasSchdedepreciationBase { get; set; }
        public string PtasSchdephysaddress { get; set; }
        public string PtasSchdeproptype { get; set; }
        public decimal? PtasSchdfdepreciation { get; set; }
        public decimal? PtasSchdfdepreciationBase { get; set; }
        public bool? PtasSsstatement { get; set; }
        public decimal? PtasTaxnontaxbonds { get; set; }
        public decimal? PtasTaxnontaxbondsBase { get; set; }
        public decimal? PtasTotalexpenses { get; set; }
        public decimal? PtasTotalexpensesBase { get; set; }
        public decimal? PtasTotalincome { get; set; }
        public decimal? PtasTotalincomeBase { get; set; }
        public decimal? PtasTrustpartnershipestateincome { get; set; }
        public decimal? PtasTrustpartnershipestateincomeBase { get; set; }
        public int? Statecode { get; set; }
        public int? Statuscode { get; set; }
        public int? Timezoneruleversionnumber { get; set; }
        public int? Utcconversiontimezonecode { get; set; }
        public long? Versionnumber { get; set; }
        public Guid? CreatedbyValue { get; set; }
        public Guid? CreatedonbehalfbyValue { get; set; }
        public Guid? ModifiedbyValue { get; set; }
        public Guid? ModifiedonbehalfbyValue { get; set; }
        public Guid? OwneridValue { get; set; }
        public Guid? OwningbusinessunitValue { get; set; }
        public Guid? OwningteamValue { get; set; }
        public Guid? OwninguserValue { get; set; }
        public Guid? PtasContactidValue { get; set; }
        public Guid? PtasMedicareplanidValue { get; set; }
        public Guid? PtasParceldetailidValue { get; set; }
        public Guid? PtasReviewedbyidValue { get; set; }
        public Guid? PtasSeappdetailidValue { get; set; }
        public Guid? PtasSeapplicationidValue { get; set; }
        public Guid? PtasYearidValue { get; set; }
        public Guid? TransactioncurrencyidValue { get; set; }
    }
}
