using System;
using System.Collections.Generic;

namespace PTASODataLibrary.PtasDbDataProvider.PtasCamaModel
{
    public partial class PtasLowincomehousingunits
    {
        public Guid PtasLowincomehousingunitsid { get; set; }
        public DateTimeOffset? Createdon { get; set; }
        public decimal? Exchangerate { get; set; }
        public int? Importsequencenumber { get; set; }
        public DateTimeOffset? Modifiedon { get; set; }
        public DateTimeOffset? Overriddencreatedon { get; set; }
        public decimal? PtasIacCapitalizationRate { get; set; }
        public decimal? PtasIacEffectivegrossincome { get; set; }
        public decimal? PtasIacEffectivegrossincomeBase { get; set; }
        public decimal? PtasIacExpenseamount { get; set; }
        public decimal? PtasIacExpenseamountBase { get; set; }
        public decimal? PtasIacExpensespct { get; set; }
        public decimal? PtasIacExpensespctBase { get; set; }
        public decimal? PtasIacIndicatedvalue { get; set; }
        public decimal? PtasIacIndicatedvalueBase { get; set; }
        public decimal? PtasIacNetoperatingincome { get; set; }
        public decimal? PtasIacNetoperatingincomeBase { get; set; }
        public decimal? PtasIacOtherincome { get; set; }
        public decimal? PtasIacOtherincomeBase { get; set; }
        public decimal? PtasIacPotentialgrossincome { get; set; }
        public decimal? PtasIacPotentialgrossincomeBase { get; set; }
        public decimal? PtasIacTotalgrossincome { get; set; }
        public decimal? PtasIacTotalgrossincomeBase { get; set; }
        public decimal? PtasIacVacancyandcreditlossamount { get; set; }
        public decimal? PtasIacVacancyandcreditlossamountBase { get; set; }
        public decimal? PtasIacVacancyandcreditlosspercent { get; set; }
        public decimal? PtasIndicatedrent1bedroom { get; set; }
        public decimal? PtasIndicatedrent1bedroomBase { get; set; }
        public decimal? PtasIndicatedrent2bedroom { get; set; }
        public decimal? PtasIndicatedrent2bedroomBase { get; set; }
        public decimal? PtasIndicatedrent2bedroom2bath { get; set; }
        public decimal? PtasIndicatedrent2bedroom2bathBase { get; set; }
        public decimal? PtasIndicatedrent3bedroom { get; set; }
        public decimal? PtasIndicatedrent3bedroomBase { get; set; }
        public decimal? PtasIndicatedrent3bedroom2bath { get; set; }
        public decimal? PtasIndicatedrent3bedroom2bathBase { get; set; }
        public decimal? PtasIndicatedrent3bedroom3bath { get; set; }
        public decimal? PtasIndicatedrent3bedroom3bathBase { get; set; }
        public decimal? PtasIndicatedrent4bedroom { get; set; }
        public decimal? PtasIndicatedrent4bedroomBase { get; set; }
        public decimal? PtasIndicatedrent5plusbedroom { get; set; }
        public decimal? PtasIndicatedrent5plusbedroomBase { get; set; }
        public decimal? PtasIndicatedrentSleepingroom { get; set; }
        public decimal? PtasIndicatedrentSleepingroomBase { get; set; }
        public decimal? PtasIndicatedrentStudio { get; set; }
        public decimal? PtasIndicatedrentStudioBase { get; set; }
        public string PtasName { get; set; }
        public int? PtasNbrof100setasideunits { get; set; }
        public int? PtasNbrof120setasideunits { get; set; }
        public int? PtasNbrof20setasideunits { get; set; }
        public int? PtasNbrof30setasideunits { get; set; }
        public int? PtasNbrof35setasideunits { get; set; }
        public int? PtasNbrof40setasideunits { get; set; }
        public int? PtasNbrof45setasideunits { get; set; }
        public int? PtasNbrof50setasideunits { get; set; }
        public int? PtasNbrof60setasideunits { get; set; }
        public int? PtasNbrof70setasideunits { get; set; }
        public int? PtasNbrof80setasideunits { get; set; }
        public int? PtasNumberofmarketunits { get; set; }
        public int? PtasNumof1bedunits { get; set; }
        public int? PtasNumof2bedunits { get; set; }
        public int? PtasNumof3bedunits { get; set; }
        public int? PtasNumof4bedunits { get; set; }
        public int? PtasNumof5bedplusunits { get; set; }
        public int? PtasNumofstudiounits { get; set; }
        public decimal? PtasPercentofunitsat100 { get; set; }
        public decimal? PtasPercentofunitsat120 { get; set; }
        public decimal? PtasPercentofunitsat20 { get; set; }
        public decimal? PtasPercentofunitsat30 { get; set; }
        public decimal? PtasPercentofunitsat35 { get; set; }
        public decimal? PtasPercentofunitsat40 { get; set; }
        public decimal? PtasPercentofunitsat45 { get; set; }
        public decimal? PtasPercentofunitsat50 { get; set; }
        public decimal? PtasPercentofunitsat60 { get; set; }
        public decimal? PtasPercentofunitsat70 { get; set; }
        public decimal? PtasPercentofunitsat80 { get; set; }
        public decimal? PtasPercentofunitsatmarket { get; set; }
        public decimal? PtasPercentofunitsatrestrictedrent { get; set; }
        public decimal? PtasRestrictedrent1bed { get; set; }
        public decimal? PtasRestrictedrent1bedBase { get; set; }
        public decimal? PtasRestrictedrent2bed { get; set; }
        public decimal? PtasRestrictedrent2bedBase { get; set; }
        public decimal? PtasRestrictedrent3bed { get; set; }
        public decimal? PtasRestrictedrent3bedBase { get; set; }
        public decimal? PtasRestrictedrent4bed { get; set; }
        public decimal? PtasRestrictedrent4bedBase { get; set; }
        public decimal? PtasRestrictedrent5bedplus { get; set; }
        public decimal? PtasRestrictedrent5bedplusBase { get; set; }
        public decimal? PtasRestrictedrentSleepingroom { get; set; }
        public decimal? PtasRestrictedrentSleepingroomBase { get; set; }
        public decimal? PtasRestrictedrentStudio { get; set; }
        public decimal? PtasRestrictedrentStudioBase { get; set; }
        public decimal? PtasRra1bedroom1bathrent { get; set; }
        public decimal? PtasRra1bedroom1bathrentBase { get; set; }
        public decimal? PtasRra2bedroom1bathrent { get; set; }
        public decimal? PtasRra2bedroom1bathrentBase { get; set; }
        public decimal? PtasRra2bedroom2bathrent { get; set; }
        public decimal? PtasRra2bedroom2bathrentBase { get; set; }
        public decimal? PtasRra3bedroom1bathrent { get; set; }
        public decimal? PtasRra3bedroom1bathrentBase { get; set; }
        public decimal? PtasRra3bedroom2bathrent { get; set; }
        public decimal? PtasRra3bedroom2bathrentBase { get; set; }
        public decimal? PtasRra3bedroom3bathrent { get; set; }
        public decimal? PtasRra3bedroom3bathrentBase { get; set; }
        public decimal? PtasRra4bedroomrent { get; set; }
        public decimal? PtasRra4bedroomrentBase { get; set; }
        public decimal? PtasRra5bedroomplusrent { get; set; }
        public decimal? PtasRra5bedroomplusrentBase { get; set; }
        public decimal? PtasRraCommercialrent { get; set; }
        public decimal? PtasRraCommercialrentBase { get; set; }
        public int? PtasRraCommercialrentsqft { get; set; }
        public int? PtasRraNbrof1bedroom1bathunits { get; set; }
        public int? PtasRraNbrof2bedroom1bathunits { get; set; }
        public int? PtasRraNbrof2bedroom2bathunits { get; set; }
        public int? PtasRraNbrof3bedroom1bathunits { get; set; }
        public int? PtasRraNbrof3bedroom2bathunits { get; set; }
        public int? PtasRraNbrof3bedroom3bathunits { get; set; }
        public int? PtasRraNbrof4bedroomunits { get; set; }
        public int? PtasRraNbrof5bedroomplusunits { get; set; }
        public int? PtasRraNbrofopen1bedroomunits { get; set; }
        public int? PtasRraNbrofopen2bedroomunits { get; set; }
        public int? PtasRraNbrofsleepingroomunits { get; set; }
        public int? PtasRraNbrofstudiounits { get; set; }
        public decimal? PtasRraOpen1bedroomrent { get; set; }
        public decimal? PtasRraOpen1bedroomrentBase { get; set; }
        public decimal? PtasRraOpen2bedroomrent { get; set; }
        public decimal? PtasRraOpen2bedroomrentBase { get; set; }
        public decimal? PtasRraOtherincomeperunit { get; set; }
        public decimal? PtasRraOtherincomeperunitBase { get; set; }
        public decimal? PtasRraSleepingroomrent { get; set; }
        public decimal? PtasRraSleepingroomrentBase { get; set; }
        public decimal? PtasRraStudiorent { get; set; }
        public decimal? PtasRraStudiorentBase { get; set; }
        public DateTimeOffset? PtasRucAssessmentdate { get; set; }
        public decimal? PtasRucDiscountrate { get; set; }
        public decimal? PtasRucDiscountrateBase { get; set; }
        public decimal? PtasRucLeaseholdreversionvalue { get; set; }
        public decimal? PtasRucLeaseholdreversionvalueBase { get; set; }
        public decimal? PtasRucPresentvalueofleasholdreversion { get; set; }
        public decimal? PtasRucPresentvalueofleasholdreversionBase { get; set; }
        public decimal? PtasRucRestrictedleasedfeevalue { get; set; }
        public decimal? PtasRucRestrictedleasedfeevalueBase { get; set; }
        public DateTimeOffset? PtasRucTerminationdateplustwoyears { get; set; }
        public decimal? PtasRucTotalrestrictedusevalue { get; set; }
        public decimal? PtasRucTotalrestrictedusevalueBase { get; set; }
        public decimal? PtasRucUnrestrictedmarketvalue { get; set; }
        public decimal? PtasRucUnrestrictedmarketvalueBase { get; set; }
        public int? PtasTotalnumberofrestrictedrentunits { get; set; }
        public int? PtasTotalnumberofunits { get; set; }
        public int? PtasUtilityprogram { get; set; }
        public int? Statecode { get; set; }
        public int? Statuscode { get; set; }
        public int? Timezoneruleversionnumber { get; set; }
        public int? Utcconversiontimezonecode { get; set; }
        public long? Versionnumber { get; set; }
        public Guid? CreatedbyValue { get; set; }
        public Guid? CreatedonbehalfbyValue { get; set; }
        public Guid? ModifiedbyValue { get; set; }
        public Guid? ModifiedonbehalfbyValue { get; set; }
        public Guid? OwneridValue { get; set; }
        public Guid? OwningbusinessunitValue { get; set; }
        public Guid? OwningteamValue { get; set; }
        public Guid? OwninguserValue { get; set; }
        public Guid? PtasAssessmentyearidValue { get; set; }
        public Guid? PtasLowincomehousingprogramidValue { get; set; }
        public Guid? PtasProjectidValue { get; set; }
        public Guid? TransactioncurrencyidValue { get; set; }
    }
}
