// <copyright file="ManyToOneRelationship.cs" company="King County">
//  Copyright (c) King County. All rights reserved.
// </copyright>
// <auto-generated />
namespace D2SSyncHelpers.Services
{
    /// <summary>
    /// Info of a dynamics attribute.
    /// </summary>
    public class EntityAttribute
    {
        public string AttributeType { get; set; }
        public bool IsCustomAttribute { get; set; }
        public bool IsPrimaryId { get; set; }
        public bool IsValidODataAttribute { get; set; }
        public bool IsPrimaryName { get; set; }
        public bool IsValidForCreate { get; set; }
        public bool IsValidForUpdate { get; set; }
        public string LogicalName { get; set; }
    }
}